name: BUILD VUE 

on:
  workflow_dispatch:
  push:
    tags:
    - 'v*'

jobs:
  build-ui:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.20.1]
        
    steps:
    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2  # 设置Node.js版本
      with:
        node-version: ${{ matrix.node-version }}
 
    - name: Install dependencies
      working-directory: ../oneterm-ui
      run: ls && yarn install
 
    - name: Build Vue App
      working-directory: ../oneterm-ui
      run: yarn run build 
